# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Create release"
        uses: "hks-systeme/.github/actions/github/release/create@1.1.0"
        with:
          github-token: "${{ secrets.HKS_SYSTEME_BOT_TOKEN }}"
